### ISSUE TITLE
Remove PolarClock

### ISSUE THREAD

**Issue by aharris88** [aharris88/awesome-macos-screensavers#13]
This isn't working for me anymore. It just says Blocked Plug-in.

![screen shot 2016-11-21 at 8 46 25 am](https://cloud.githubusercontent.com/assets/3266363/20489208/040c3ae2-afc7-11e6-9b62-df408fb4ba4c.png)

**Comment by gingerbeardman** [comment]
this does not work form me either

I don't see "blocked plugin" but then I do not have flash installed on my machine.

I guess this was somehow running a webkit instance containing a flash plugin?

**Comment by aharris88** [comment]
Yeah, I'm not sure. It may be something that is no longer supported in macOS Sierra.
