### ISSUE TITLE
Update iOS Lockscreen link

### ISSUE THREAD

**Issue by aharris88** [aharris88/awesome-macos-screensavers#17]
Update the iOS Lockscreen link and make sure it still works on macOS Sierra.

**Comment by bfarayev** [comment]
Current link is (http://littleendiangamestudios.com/project/ios-7-screen-saver/) and even in the page itself, they're saying that:
> Please note that this version is technically beta due to the methods used to build the screensaver and the buggy nature of it.

I give it a go for ios-8 version of this and it seemed working on my macOS Sierra. Seems more stable and it's pretty customizable. Definitely worths being in the list.

**Comment by aharris88** [comment]
Thanks. Would you like to submit a pull request for this?

**Comment by bfarayev** [comment]
Sure.. Will do it later today.
