### ISSUE TITLE
Kernel Panic screensaver

### ISSUE THREAD

**Issue by bfarayev** [aharris88/awesome-macos-screensavers#19]
Thought that, adding this kernel panic screensaver might be fun too: https://www.macupdate.com/app/mac/23341/bsod

**Comment by aharris88** [comment]
I agree, that looks pretty cool. Do you want to submit a pull request?

https://github.com/aharris88/awesome-macos-screensavers/blob/master/contributing.md

**Comment by bfarayev** [comment]
Sure. I'll do it in some time today.
