### ISSUE TITLE
rip halproject

### ISSUE THREAD

**Issue by moses-moore-spafax** [aharris88/awesome-macos-screensavers#24]
halproject.com is no more.
Found [a copy in a heapsite](https://www.screensaversplanet.com/screensavers/hal-9000-301/) but maybe we should contact Joe Mackenzie to find a legit mirror.

**Comment by aharris88** [comment]
Thanks. I wonder if we should remove it or point to the other link you found.

**Comment by moses-moore-spafax** [comment]
The shareware "basic" version may not be sufficiently awesome.  Up to you; don't forget to scan for viruses before testing.
